export const COLOMBIA_CITIES: Record<string, string[]> = {
    'CO-AMA': ['Leticia', 'Puerto Nariño'],
    'CO-ANT': ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Apartadó', 'Rionegro', 'Turbo', 'Caucasia', 'Sabaneta', 'Chigorodó', 'Caldas', 'Copacabana', 'La Estrella', 'La Ceja', 'Marinilla', 'Guarne', 'Carmen de Viboral', 'Girardota', 'Yarumal', 'Santa Rosa de Osos'],
    'CO-ARA': ['Arauca', 'Arauquita', 'Saravena', 'Tame'],
    'CO-ATL': ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga', 'Baranoa', 'Galapa', 'Puerto Colombia'],
    'CO-BOL': ['Cartagena', 'Magangué', 'Turbaco', 'El Carmen de Bolívar', 'Arjona', 'Mompós'],
    'CO-BOY': ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Paipa', 'Puerto Boyacá', 'Villa de Leyva'],
    'CO-CAL': ['Manizales', 'La Dorada', 'Chinchiná', 'Villamaría', 'Riosucio'],
    'CO-CAQ': ['Florencia', 'San Vicente del Caguán', 'Cartagena del Chairá'],
    'CO-CAS': ['Yopal', 'Aguazul', 'Villanueva', 'Tauramena', 'Paz de Ariporo'],
    'CO-CAU': ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Patía', 'Piendamó'],
    'CO-CES': ['Valledupar', 'Aguachica', 'Agustín Codazzi', 'Bosconia'],
    'CO-CHO': ['Quibdó', 'Istmina', 'Tadó', 'Condoto'],
    'CO-COR': ['Montería', 'Lorica', 'Sahagún', 'Cereté', 'Montelíbano', 'Planeta Rica'],
    'CO-CUN': ['Soacha', 'Facatativá', 'Fusagasugá', 'Zipaquirá', 'Chía', 'Girardot', 'Mosquera', 'Madrid', 'Funza', 'Cajicá', 'Tocancipá', 'Cota', 'Sibaté', 'Villeta'],
    'CO-DC': ['Bogotá D.C.'],
    'CO-GUA': ['Inírida'],
    'CO-GUV': ['San José del Guaviare'],
    'CO-HUI': ['Neiva', 'Pitalito', 'Garzón', 'La Plata'],
    'CO-LAG': ['Riohacha', 'Maicao', 'Uribia', 'Manaure', 'San Juan del Cesar'],
    'CO-MAG': ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato'],
    'CO-MET': ['Villavicencio', 'Acacías', 'Granada', 'Puerto López'],
    'CO-NAR': ['Pasto', 'Tumaco', 'Ipiales', 'La Unión', 'Túquerres'],
    'CO-NSA': ['Cúcuta', 'Ocaña', 'Villa del Rosario', 'Los Patios', 'Pamplona', 'Tibú'],
    'CO-PUT': ['Mocoa', 'Puerto Asís', 'Orito', 'Sibundoy'],
    'CO-QUI': ['Armenia', 'Calarcá', 'La Tebaida', 'Montenegro', 'Quimbaya', 'Circasia'],
    'CO-RIS': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia'],
    'CO-SAP': ['San Andrés', 'Providencia'],
    'CO-SAN': ['Bucaramanga', 'Floridablanca', 'Barrancabermeja', 'Girón', 'Piedecuesta', 'San Gil', 'Socorro', 'Vélez'],
    'CO-SUC': ['Sincelejo', 'Corozal', 'San Marcos', 'San Onofre'],
    'CO-TOL': ['Ibagué', 'Espinal', 'Melgar', 'Chaparral', 'Líbano', 'Mariquita'],
    'CO-VAC': ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Yumbo', 'Cartago', 'Jamundí', 'Buga', 'Candelaria', 'Florida', 'Pradera'],
    'CO-VAU': ['Mitú'],
    'CO-VID': ['Puerto Carreño']
};

export const COLOMBIA_STATES = [
    { code: 'CO-AMA', name: 'Amazonas' },
    { code: 'CO-ANT', name: 'Antioquia' },
    { code: 'CO-ARA', name: 'Arauca' },
    { code: 'CO-ATL', name: 'Atlántico' },
    { code: 'CO-BOL', name: 'Bolívar' },
    { code: 'CO-BOY', name: 'Boyacá' },
    { code: 'CO-CAL', name: 'Caldas' },
    { code: 'CO-CAQ', name: 'Caquetá' },
    { code: 'CO-CAS', name: 'Casanare' },
    { code: 'CO-CAU', name: 'Cauca' },
    { code: 'CO-CES', name: 'Cesar' },
    { code: 'CO-CHO', name: 'Chocó' },
    { code: 'CO-COR', name: 'Córdoba' },
    { code: 'CO-CUN', name: 'Cundinamarca' },
    { code: 'CO-DC', name: 'Bogotá D.C.' },
    { code: 'CO-GUA', name: 'Guainía' },
    { code: 'CO-GUV', name: 'Guaviare' },
    { code: 'CO-HUI', name: 'Huila' },
    { code: 'CO-LAG', name: 'La Guajira' },
    { code: 'CO-MAG', name: 'Magdalena' },
    { code: 'CO-MET', name: 'Meta' },
    { code: 'CO-NAR', name: 'Nariño' },
    { code: 'CO-NSA', name: 'Norte de Santander' },
    { code: 'CO-PUT', name: 'Putumayo' },
    { code: 'CO-QUI', name: 'Quindío' },
    { code: 'CO-RIS', name: 'Risaralda' },
    { code: 'CO-SAP', name: 'San Andrés y Providencia' },
    { code: 'CO-SAN', name: 'Santander' },
    { code: 'CO-SUC', name: 'Sucre' },
    { code: 'CO-TOL', name: 'Tolima' },
    { code: 'CO-VAC', name: 'Valle del Cauca' },
    { code: 'CO-VAU', name: 'Vaupés' },
    { code: 'CO-VID', name: 'Vichada' }
];
